version: '3.8'

services:

  app:
    container_name: easy_model
    build:
      context: .
      dockerfile: DockerFile

    volumes:
      - .:/workspaces:cached

    working_dir: /workspaces

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Restart if stopped
    restart: unless-stopped

volumes:
   django-modeler-dev:
