name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: '5.38.0'
        install-modules-with: cpanm
        install-modules-args: --with-develop --with-configure

    - name: Install test dependencies
      run: |
          cpanm --quiet --notest Test::MockFile
          cpanm --quiet --notest Test::MockObject
          cpanm --quiet --notest Module::Build
          cpanm --quiet --notest Devel::Cover
          coanm --quiet --notest Devel::Cover::Report::Codecovbash

    - name: Run tests and get coverage
      env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
          perl Build.pl
          cover -test -report codecov
